### ISSUE TITLE
Form submit not working without SSR

### ISSUE THREAD

**Issue by Nutomic** [tlowerison/leptos_form#18]
Hi, Im trying to use this crate in a project that only uses client-side rendering (using trunk). I copied the example from the readme with [minimal changes](https://github.com/Nutomic/ibis/blob/0052054a192cb485e7f9673fa45f33333844f7a1/src/frontend/login.rs). The problem is that form submission doesnt work at all, not even an error is logged. I suspect this is because `action` should be a `#[server]` function but that is not possible in my case. 

Would it be possible to make the `action` optional? Then it should be possible to handle submissions on the client side using `on_success`. Alternatively `action` itself could support client-side functions.

By the way I noticed that [Component attributes](https://docs.rs/leptos_form/latest/leptos_form/derive.Form.html#component-attributes) documentation is outdated, `submit` doesnt exist anymore.

Edit: Ive implemented csr-only forms manually now, without leptos_form and using `form on:submit`. It would be nice if leptos_form could support this with an `on_submit` parameter on component. [Code is here](https://github.com/Nutomic/ibis/blob/90d92f53915124be8341934618c2083b79fa29eb/src/frontend/login.rs)

**Comment by tlowerison** [comment]
Hi @Nutomic thanks for the issue report! Sorry for the delay in my reply.

I think making `action` optional is a good idea and adding a new `on_submit` parameter rather than trying to cram it into `action` will help keep the macro from becoming too confusing. Imo they shouldn't be used simultaneously to avoid ambiguity in terms of runtime behavior at form submission, and that can just be documented in the `Form` macro docs + a compile time error in the actual proc macro.

I've pushed a [branch](https://github.com/leptos-form/leptos_form/blob/on_submit/proc_macros/docs/Form/README.md) which supports passing `on_submit` with a callback expression that will take two parameters:
- `Self`, the type which is having `Form` derived on
- [SubmitEvent](https://docs.rs/leptos/latest/leptos/ev/struct.SubmitEvent.html)

In addition, I've updated the derived Form component to allow using `on_success` and `on_error` as long as either `on_submit` is used OR `action` is used specifying a path to a server function (cannot work if `action` specifies a url string). This is made possible by actually using the callback provided as `on_submit` inside of an action using [create_action](https://docs.rs/leptos/latest/leptos/fn.create_action.html). This does restrict the `on_submit` expression to returning a type of `impl Future<Output = Result<T, E>>` with no restrictions on `T` or `E`. All of this will be referenced in the derive macro docs of `Form` and a specific trait will be exported that people can reference called `OnSubmit` that will hopefully provide some clarity as well.

Here's a slightly reworked version of your example code using these attribute parameters now:
```rust
use ::leptos::*;
use ::leptos_form::prelude::*;
use ::serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Default, Form, Serialize)]
#[form(component(
    on_submit = |my_data, ev| {
        ev.prevent_default();
        create_my_data(my_data)
    },
    on_error = |err, ev| logging::log!("{err}"),
    on_success = |ok, ev| logging::log!("{ok:?}"),
))]
pub struct MyData {
    pub username: String,
    pub password: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct DbMyData {
    pub id: i32,
    pub name: String,
}

async fn create_my_data(my_data: MyData) -> Result<DbMyData, String> {
    Ok(DbMyData {
        id: 1,
        name: my_data.username,
    })
}

#[component]
pub fn Home() -> impl IntoView {
    view! {
        <MyData
            initial={MyData::default()}
            bottom=|| view!(<input style:cursor="pointer" type="submit" value="Login" />)
        />
    }
}
```

Hopefully this helps make `leptos_form` integrate with CSR much more smoothly! Let me know what you think.

PS Thank you for making the note about the missing `submit` parameter, I've removed that from the docs as it was replaced by the `top` and `bottom` props that are used by the generated component (Note to self that I need to add documentation for those props).

**Comment by Nutomic** [comment]
Thank you! For now I moved on to other parts of the code, but will get back to this later.

**Comment by Nutomic** [comment]
Well getting this working in my project requires upgrading lots of dependencies which is currently blocked by upstream. So I have do to it later. Gonna close the issue anyway, thanks again!
